<!DOCTYPE html>
<html>
<head>
    <title>
        videoWallsUsersRouter Homepage
    </title>
</head>
<body>
<div align="center">
    <h1>This is generated by <a href="https://www.linkedin.com/in/mritunjoy-das-1004aa138/">Joeydash</a></h1>
    Your example resource is <a href="/api/v1/example/whatever_you_type_here">here</a>
    </div>
</body>
</html>